{% set name = "jupyter-nbmodel-client" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace("-", "_") }}-{{ version }}.tar.gz
  sha256: b9bc91b834280f7e0d4842e64557c8e5ebde51a119275993a2abbe900972617b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.21.0,<2.0.0
  run:
    - python >={{ python_min }}
    - jupyter_ydoc >=2.1.2,<4.0.0
    - nbformat >=5.0.0,<6.0.0
    - pycrdt >=0.10.3,<0.13.0
    - requests
    - websockets >=14.0.0

test:
  imports:
    - jupyter_nbmodel_client
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/datalayer/jupyter-nbmodel-client
  summary: 'Client to interact with Jupyter notebook model.'
  description: |
    Client to interact with Jupyter notebook model through websocket
    and CRDT model (aka collaborative model).
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - echarles
    - fcollonval
